name: mobius-platform

services:
    mysql:
        container_name: "mysql-container"
        build: "./mysql"
        env_file: ".env"
        restart: always
        ports:
            - "3306:3306"
