name: mobius-platform

services:
    mysql:
        container_name: "mysql-container"
        build: "./mysql"
        env_file: ".env"
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql


volumes:
    db-data:
        name: "mysql-data"
